# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty


# Setup
title:               'Swift: On The Server'
tagline:             'You''re a fullstack developer, Harry!'
description:         'Write swift on the backend and on the client!'
url:                 http://swiftfullstack.com/
baseurl:             'http://swiftfullstack.com/'
paginate:            1

# About/contact
author:
  name:              James Graham
  url:               https://twitter.com/wittedhaddock
  email:             help@caffei.net

# Custom vars
version:             1.0.0

gems: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"
